//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitizingDataAdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupSupport
    {
        public int SupportId { get; set; }
        public string SupportType { get; set; }
        public int VslaId { get; set; }
        public int TrainerId { get; set; }
        public System.DateTime SupportDate { get; set; }
    
        public virtual Cbt_info Cbt_info { get; set; }
        public virtual Vsla Vsla { get; set; }
    }
}
