//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitizingDataAdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanRepayment
    {
        public int RepaymentId { get; set; }
        public Nullable<int> RepaymentIdEx { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> BalanceAfter { get; set; }
        public Nullable<decimal> BalanceBefore { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> LastDateDue { get; set; }
        public Nullable<System.DateTime> NextDateDue { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<decimal> RolloverAmount { get; set; }
        public Nullable<int> MeetingId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> LoanId { get; set; }
    
        public virtual LoanIssue LoanIssue { get; set; }
        public virtual Meeting Meeting { get; set; }
        public virtual Member Member { get; set; }
    }
}
