//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitizingDataAdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Fines = new HashSet<Fine>();
            this.LoanIssues = new HashSet<LoanIssue>();
            this.LoanRepayments = new HashSet<LoanRepayment>();
            this.Savings = new HashSet<Saving>();
        }
    
        public int MemberId { get; set; }
        public Nullable<int> MemberIdEx { get; set; }
        public Nullable<int> MemberNo { get; set; }
        public Nullable<int> CyclesCompleted { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string Gender { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> DateArchived { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> VslaId { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<Fine> Fines { get; set; }
        public virtual ICollection<LoanIssue> LoanIssues { get; set; }
        public virtual ICollection<LoanRepayment> LoanRepayments { get; set; }
        public virtual Vsla Vsla { get; set; }
        public virtual ICollection<Saving> Savings { get; set; }
    }
}
