//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitizingDataAdminWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSubmission_20140113_2
    {
        public int SubmissionId { get; set; }
        public string SourceVslaCode { get; set; }
        public string SourcePhoneImei { get; set; }
        public string SourceNetworkOperator { get; set; }
        public string SourceNetworkType { get; set; }
        public Nullable<System.DateTime> SubmissionTimestamp { get; set; }
        public string Data { get; set; }
        public Nullable<bool> ProcessedFlag { get; set; }
    }
}
