//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitizingDataAdminWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Fines = new HashSet<Fine>();
            this.Fines1 = new HashSet<Fine>();
            this.Fines2 = new HashSet<Fine>();
            this.LoanIssues = new HashSet<LoanIssue>();
            this.LoanRepayments = new HashSet<LoanRepayment>();
            this.Savings = new HashSet<Saving>();
        }
    
        public int MeetingId { get; set; }
        public Nullable<int> MeetingIdEx { get; set; }
        public Nullable<decimal> CashExpenses { get; set; }
        public Nullable<decimal> CashFines { get; set; }
        public Nullable<decimal> CashFromBank { get; set; }
        public Nullable<decimal> CashFromBox { get; set; }
        public Nullable<decimal> CashSavedBank { get; set; }
        public Nullable<decimal> CashSavedBox { get; set; }
        public Nullable<decimal> CashWelfare { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public Nullable<bool> IsDataSent { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<int> CountOfMembersPresent { get; set; }
        public Nullable<decimal> SumOfSavings { get; set; }
        public Nullable<decimal> SumOfLoanIssues { get; set; }
        public Nullable<decimal> SumOfLoanRepayments { get; set; }
        public Nullable<int> CycleId { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<Fine> Fines { get; set; }
        public virtual ICollection<Fine> Fines1 { get; set; }
        public virtual ICollection<Fine> Fines2 { get; set; }
        public virtual ICollection<LoanIssue> LoanIssues { get; set; }
        public virtual ICollection<LoanRepayment> LoanRepayments { get; set; }
        public virtual VslaCycle VslaCycle { get; set; }
        public virtual ICollection<Saving> Savings { get; set; }
    }
}
