//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitizingDataAdminWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VslaDdActivation
    {
        public int ActivationId { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PassKey { get; set; }
        public string PhoneImei01 { get; set; }
        public string PhoneImei02 { get; set; }
        public string SimImsiNo01 { get; set; }
        public string SimImsiNo02 { get; set; }
        public string SimNetworkOperator01 { get; set; }
        public string SimNetworkOperator02 { get; set; }
        public string SimSerialNo01 { get; set; }
        public string SimSerialNo02 { get; set; }
        public Nullable<int> VslaId { get; set; }
    
        public virtual Vsla Vsla { get; set; }
    }
}
